name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build
      run: cargo build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: lib_${{ matrix.os }}
        path: target/debug/build/**/out/lib
