name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Download deps
      run: |
         if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
         fi
      shell: bash
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Build
      run: cargo build
